collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.688172
color:
  saturation: 0.3709677
  brandStrength: 0.5376344
  lightness: 0.213793
  brandColors:
    - '#FFFFFF'
    - '#151515'
    - '#125688'
    - '#A5A7AA'
    - '#39BDCF'
  rhythmicContrast: 0
layout_spectrum: 0.06989247
name: catalysts
