layout_spectrum: 0.3365637
typography_spectrum: 0.3020672
color:
  saturation: 0.6481673
  lightness: 0.213793
  brandStrength: 0.004609307
  rhythmicContrast: 0.4513426
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: catalysts
